CREATE TABLE MEMBERS (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(30), AGE INT, SEX VARCHAR(20));
CREATE TABLE RELATIONSHIP (ID1 INT PRIMARY KEY , ID2 INT,RELATION VARCHAR(30));
ALTER TABLE RELATIONSHIP DROP PRIMARY KEY, ADD PRIMARY KEY(ID1, ID2);

